site_name: LoRa Gateway Bridge documentation
repo_url: https://github.com/brocaar/lora-gateway-bridge
theme_dir: docs/material
include_next_prev: False

pages:
  - index.md
  - deployment.md
  - getting-started.md
  - topics.md
  - frequently-asked-questions.md
  - changelog.md
  - Gateways:
    - Airfy GateBoard AYTGB-137-8: gateways/airfy-gateboard-aytgb-137-8.md
    - IMST iC880A: gateways/imst-ic880a.md
    - Kerlink IoT Station: gateways/kerlink-iot-station.md

extra:
  version: '2.1.2'
  github:
    download_release: true

markdown_extensions:
  - admonition
  - codehilite(css_class=code)

google_analytics: ['UA-3512995-9', 'docs.loraserver.io']

extra_javascript:
  - static/js/gitter.js
  - https://sidecar.gitter.im/dist/sidecar.v1.js
